CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]

macos_min_version:             # [osx]
  - 10.9                       # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]

mpi:
  - moose-mpich

SHORT_VTK_NAME:
  - 6.3

netcdf:
 - 4.6.2

libpng:
  - 1.6.37 h2573ce8_0 # [osx]
  - 1.6.37 hed695b0_0 # [linux]

moose_petsc:
 - 3.14.2 build_4

moose_libmesh_vtk:
 - 6.3.0 build_5

pin_run_as_build:
  moose_petsc: x.x.x
  moose_libmesh_vtk: x.x.x
