{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set version = "2021.04.06" %}

package:
  name: moose-libmesh
  version: {{ version }}

source:
  path: ../../libmesh

build:
  number: {{ build }}
  string: {{ strbuild }}
  skip: true                                            # [win]

requirements:
  build:
    - pkg-config
    - cctools                                           # [osx]
    - ld64                                              # [osx]
    - moose-libmesh-vtk {{ moose_libmesh_vtk }}
    - moose-petsc {{ moose_petsc }}

  run:
    - pkg-config
    - libnetcdf {{ netcdf }}                            # [linux]
    - moose-libmesh-vtk {{ moose_libmesh_vtk }}
    - moose-petsc {{ moose_petsc }}
    - libpng {{ libpng }}

test:
  commands:
    - test -f $PREFIX/libmesh/lib/libmesh_opt.dylib     # [osx]
    - test -f $PREFIX/libmesh/lib/libmesh_opt.so        # [linux]
    - test -f $PREFIX/libmesh/lib/libmetaphysicl.dylib  # [osx]
    - test -f $PREFIX/libmesh/lib/libmetaphysicl.so     # [linux]
    - test -f $PREFIX/libmesh/lib/libtimpi_opt.dylib    # [osx]
    - test -f $PREFIX/libmesh/lib/libtimpi_opt.so       # [linux]

about:
  home: http://libmesh.github.io/
  license: LGPL
  summary: 'The libMesh library provides a framework for the numerical simulation of partial differential equations using arbitrary unstructured discretizations on serial and parallel platforms'

extra:
  recipe-maintainers:
    - milljm
