CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.10.sdk       # [osx]

macos_min_version:             # [osx]
  - 10.10                      # [osx]

macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]

MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.10                      # [osx]

moose_libmesh:
  - 2020.11.04 build_0         # [osx]
  - 2020.11.04 build_1         # [linux]

pr_num:
  - 12345
