{% set build = 0 %}
{% set version = "2021.01.06" %}

package:
  name: moose-tools
  version: {{ version }}

source:
  path: ../tools

build:
  number: {{ build }}
  skip: True # [not linux]
  noarch: python

requirements:
  host:
    - python >=3.6,<3.8
    - vtk 8.2.0

  run:
    - python >=3.6,<3.8
    - vtk 8.2.0
    - numpy
    - pyqt
    - matplotlib
    - pandas
    - livereload
    - yaml
    - pyyaml
    - beautifulsoup4
    - pybtex
    - mock
    - lxml
    - scikit-image
    - pylatexenc
    - jinja2
    - mako

test:
  imports:
    - numpy
    - PyQt5
    - matplotlib
    - pandas
    - livereload
    - yaml
    - bs4
    - pybtex
    - mock
    - lxml
    - skimage
    - vtk
    - pylatexenc
    - jinja2

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'This superficial module (moose-tools) acts as a top-level module designed to provide all dependencies required in order to run Peacock and MOOSE Documentation.'

extra:
  recipe-maintainers:
    - milljm
