{% set build = 0 %}
{% set version = "2020.12.17" %}

package:
  name: moose-pyhit
  version: {{ version }}

source:
  git_url: https://github.com/milljm/moose-pyhit.git

build:
  number: {{ build }}  # [linux,osx]
  skip: true           # [win]

requirements:
  build:
    - gxx_linux-64 {{ gxx }}                 # [linux]
    - clangxx      {{ clangxx }}             # [osx]
    - python       {{ python }}
    - cython

  host:
    - gxx_linux-64 {{ gxx }}                 # [linux]
    - clangxx      {{ clangxx }}             # [osx]
    - python       {{ python }}
    - cython

  run:
    - gxx_linux-64 {{ gxx }}                 # [linux]
    - clangxx      {{ clangxx }}             # [osx]
    - python       {{ python }}

test:
  imports:
    - pyhit

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'HIT Parser'

extra:
  recipe-maintainers:
    - milljm
